### ISSUE TITLE
Don't check in .pyc files in a repository

### ISSUE THREAD

**Issue by pradyunsg** [shubhodeep9/GitChat#1]
Just putting it out there.

**Comment by shubhodeep9** [comment]
Can you please elaborate @pradyunsg

**Comment by pradyunsg** [comment]
.py files are the code. .pyc files are build-artifact like. Consider adding a .gitignore file and doing a git rm *.pyc (IIRC).

**Comment by pradyunsg** [comment]
Here's something: https://coderwall.com/p/wrxwog/why-not-to-commit-pyc-files-into-git-and-how-to-fix-if-you-already-did
