### ISSUE TITLE
gh-pages compress images

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/GitChat#2]
Compress images of the website hosted in branch `gh-pages`

**Comment by schamp** [comment]
I can take a stab at this.  Any particular compression criteria in mind, or just "smaller, and not with horrible artifacts"?

**Comment by shubhodeep9** [comment]
@schamp Just smaller in size for better load time.

**Comment by gabrielpaivadev** [comment]
I make it #5

**Comment by shubhodeep9** [comment]
@gpgabrielpaiva Cool
