### ISSUE TITLE
Various issues with the gh-pages website

### ISSUE THREAD

**Issue by JamesMCo** [shubhodeep9/GitChat#4]
- There is no download link/are no instructions on how to install the project
- There are a couple of typos and other grammatical errors on the page
- The copyright info in the footer doesn't include 2017

**Comment by shubhodeep9** [comment]
@JamesMCo Hi, so I will merge the PR, I have reviewed it and it looks fine to me.
Why don't you go ahead and star the repo.
Cheers!!!
